# .github/workflows/ci.yml
name: Multi-Branch CI Pipeline

# When should this workflow run?
on:
  push:
    branches: [main, staging, development]

# Define the jobs
jobs:
  # Basic tests that run on ALL branches
  basic-tests:
    name: Basic Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  # Docker build test - only on staging and main branches
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: basic-tests
    # Only run on staging and main branches
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ github.sha }} .
          echo "Docker image built successfully!"

      - name: Test Docker container
        run: |
          # Start container in background
          docker run -d -p 3000:3000 --name test-container my-app:${{ github.sha }}

          # Wait for container to start
          sleep 10

          # Test if it responds
          curl -f http://localhost:3000/health || exit 1

          # Clean up
          docker stop test-container
          docker rm test-container
